baseurl: /poker
permalink: /advisor/blog/:year-:month-:day-:title
highlighter: rouge
exclude: [advisor/Design, advisor/Content]
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-redirect-from